apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
spec:
  destination:
    name: ''
    namespace: crossplane
    server: 'https://kubernetes.default.svc'
  source:
    path: crossplane
    repoURL: 'https://github.com/UriZafrir/crossplane-examples.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated: null
