apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  resources:
    - name: rds-resource
      base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Instance
        metadata:
          annotations:
            meta.upbound.io/example-id: rds/v1beta1/instanceroleassociation
            uptest.upbound.io/timeout: "3600"
          labels:
            testing.upbound.io/example-name: commit-dbinstance-ira
          name: commit-dbinstance-${Rand.RFC1123Subdomain}
        spec:
          forProvider:
            allocatedStorage: 20
            autoGeneratePassword: true
            autoMinorVersionUpgrade: true
            backupRetentionPeriod: 14
            backupWindow: 09:46-10:16
            dbName: commit-db
            engine: postgres
            engineVersion: "13.7"
            instanceClass: db.t2.micro #was db.t3.micro
            kmsKeyIdSelector:
              matchLabels:
                testing.upbound.io/example-name: sample-key-ira
            maintenanceWindow: Mon:00:00-Mon:03:00
            passwordSecretRef:
              key: password
              name: commit-dbinstance
              namespace: upbound-system
            publiclyAccessible: false
            region: {{ .Values.region }}
            skipFinalSnapshot: true
            storageEncrypted: true
            storageType: gp2
            username: admin
          writeConnectionSecretToRef:
            name: commit-dbinstance-out
            namespace: default
    - name: security-group-resource
      base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        metadata:
          labels:
            testing.upbound.io/example-name: securitygroup1
          name: example
        spec:
          forProvider:
            description: Allow 3306
            name: allow_3306
            region: {{ .Values.region }}
            tags:
              Name: allow_3306
            vpcIdSelector:
              matchLabels:
                testing.upbound.io/example-name: securitygroup1
