apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: {{ .Values.vpc_name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    cidrBlock: {{ .Values.vpc_cidr }}
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: example

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: commit-subnet1
spec:
  forProvider:
    region: {{ .Values.region }}
    availabilityZone: {{ .Values.availabilityZone.a }}
    cidrBlock:  {{ .Values.subnet_cidr.subnet1 }}
    vpcIdRef:
      name: {{ .Values.vpc_name }}
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: example

---

apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: commit-subnet2
spec:
  forProvider:
    region: {{ .Values.region }}
    availabilityZone: {{ .Values.availabilityZone.b }}
    cidrBlock:  {{ .Values.subnet_cidr.subnet2 }}
    vpcIdRef:
      name: {{ .Values.vpc_name }}
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: example