apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: {{ .Values.vpc-name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    cidrBlock: {{ .Values.vpc-cidr }}
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
  providerConfigRef:
    name: example

---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: commit-subnet1
spec:
  forProvider:
    region: {{ .Values.region }}
    availabilityZone: {{ .Values.availabilityZone.1a }}
    cidrBlock:  {{ .Values.subnet-cidr.subnet1 }}
    vpcIdRef:
      name: {{ .Values.vpc-name }}
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: example
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: commit-subnet2
spec:
  forProvider:
    region: {{ .Values.region }}
    availabilityZone: {{ .Values.availabilityZone.1b }}
    cidrBlock:  {{ .Values.subnet-cidr.subnet2 }}
    vpcIdRef:
      name: {{ .Values.vpc-name }}
    mapPublicIPOnLaunch: true
  providerConfigRef:
    name: example